apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudapi-pod
spec:
  selector:
    matchLabels:
      run: cloudapi-pod
  replicas: 2
  template:
    metadata:
      labels:
        run: cloudapi-pod
    spec:
      containers:
      - name: cloudapi-pod
        image: vitoribb/cloud-api:latest
        ports:
          - containerPort: 80
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
apiVersion: v1
kind: Service
metadata:
  name: cloudapi-pod
  labels:
    run: cloudapi-pod
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    run: cloudapi-pod
